name = "sim-miu-app"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "sim-ppds-db-v2"
database_id = "27ec7392-6ac2-4bdc-8570-69ab4057e485"
